### ISSUE TITLE
Add best practice guide for using bash aliasing to make shorter commands

### ISSUE THREAD

**Issue by djgroen** [djgroen/FabSim3#139]
I personally use bash aliases to shorten `fabsim eagle_hidalgo` to `feh`, which really saves on typing individual commands, and using the toolkit.

In fact I think it's so useful that it may be worth inserting that in the documentation somewhere.

I don't know what place is appropriate for that currently though, perhaps we could make a best practices in automation guide in the `docs` section?

**Comment by arabnejad** [comment]
Hi @djgroen 
I made the first prototype for this functionality, github branch : [bash_aliasing](https://github.com/djgroen/FabSim3/tree/bash_aliasing)
usage : 
`fabsim <machine_name> bash_alias:<alias_name> `

since that the user added `/FaSim3/bin` folder to the `.bashrc` file, so by reloading that file `source ~/.bashrc` or restarting the shell, the new command should be available to be used

**Comment by djgroen** [comment]
@arabnejad Very interesting. Could you add a simple example to the `docs` on how to use this aliasing?

**Comment by djgroen** [comment]
Renamed `bash_alias` to `bash_machine_alias` to avoid confusion. Also added a check to avoid overwriting the `fabsim` command.

**Comment by djgroen** [comment]
See commit 97e0a559e6cd1a008171d1d3d7a407825c536e0e

**Comment by djgroen** [comment]
And I added documentation, so this is all done and dusted now.
