### ISSUE TITLE
SSH error connection when submitting a large number of ensemble runs

### ISSUE THREAD

**Issue by arabnejad** [djgroen/FabSim3#190]
FabSim3 provided a multi-threading functionality to decrease the total job submission time for a large number of ensemble/replica
however, we the ensemble runs are really high (>30k) due to a high number of SSH connection, the submission process may FAILED 
```
    ...
    raise SSHException("SSH session not active")
paramiko.ssh_exception.SSHException: SSH session not active
```
there are a number of ways that we can handle this issue, but there will be degradation on total submission time 

what do you think @djgroen ? what are your suggestions to tackle this issue?

**Comment by djgroen** [comment]
Okay, I think this is one part that is responsible for all the SSH connections. There are three run commands right after this line:
https://github.com/djgroen/FabSim3/blob/510dc58b0aca78fe92b6ad13d60dfb2685e2223e/base/fab.py#L596

Any command with run() in job will scale the number of SSH connections by the job count. These need to be merged such that file staging is done for all jobs (or at least multiple jobs) in one go, rather than separately for each job.


Later on there is also this line:
https://github.com/djgroen/FabSim3/blob/510dc58b0aca78fe92b6ad13d60dfb2685e2223e/base/fab.py#L659
That line changes permission for one file for each job. That one may actually be straightforward to refactor, because I think you can just chmod all subdirs in that results dir with a single command at the right time (i.e. after everything is uploaded)?


Lastly, there are several run commands after this line
https://github.com/djgroen/FabSim3/blob/510dc58b0aca78fe92b6ad13d60dfb2685e2223e/base/fab.py#L696
but those are merged in the case of QCG-PJ ensembles, so I think that part can remain unchanged.

Does this help things @arabnejad ?

**Comment by arabnejad** [comment]
I reduced the number of SSH connection during the job submission (https://github.com/djgroen/FabSim3/commit/c8cfadc92823d11abd863d82cf4ba57568e54ddc, https://github.com/djgroen/FabSim3/commit/d162081e5a7196b46ee7dee71130888444f5f4b5)

Federica (@FGugole) could you please confirm that new implementation fixed your problem
also, could you please mention the campaign size that you used, and the total submission time

**Comment by FGugole** [comment]
Yes, the new implementation fixed my problem and I was able to submit a campaign with 60k samples. The job submission took a long time (at least 10 days), but it was successful!
