### ISSUE TITLE
DeprecationWarning in configure_fabsim.py

### ISSUE THREAD

**Issue by Thinkpiet** [djgroen/FabSim3#303]
Hi,

when I follow the installation instructions [here](https://fabsim3.readthedocs.io/en/latest/installation/) and execute `python3 configure_fabsim.py`, I get this
```
 FabSim3/configure_fabsim.py:3: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
```

It is only a warning that can safely be ignored (installation is successful anyway), but I am documenting it with this issue :-)

Best, Piet

### Platform details

 - OS: Arch Linux
 - Python version: Python 3.12.6

**Comment by mzrghorbani** [comment]
Hi team,

I've investigated the DeprecationWarning in configure_fabsim.py related to pkg_resources. The warning occurs because pkg_resources is imported but not actually used in the code.

**Suggested Resolution:** To resolve this warning, you can simply remove the unused import statement:

import pkg_resources

**Removing this line eliminates the warning without affecting the functionality of configure_fabsim.py. I’ve tested this change, and it works as expected.**

Would someone with commit access be able to review and merge this fix? Please let me know if I can provide any further assistance!

Thank you!
