### ISSUE TITLE
$HOME/.local/bin might be in PATH twice

### ISSUE THREAD

**Issue by Thinkpiet** [djgroen/FabSim3#304]
https://github.com/djgroen/FabSim3/blob/20c62f52db9c94e8bd46bda6f145afb04bea7897/configure_fabsim.py#L239

I think the script should check here if `~/.local/bin` is in `$PATH` already (for me it was, before I installed FabSim3). In that case, that message should not be printed. That would avoid unnecessary duplicate entries in `$PATH`.

**Comment by mzrghorbani** [comment]
Hi team,

Thank you for pointing out the potential for duplicate entries in $PATH. I've reviewed the code and suggested a solution to check if ~/.local/bin is already in $PATH before adding it to the message.

**Proposed Update:**
By modifying the script to include a conditional check, we can ensure that ~/.local/bin is only added if it isn’t already in $PATH. Here’s the code snippet with the update:

title = "[orange_red1]Congratulation :clinking_beer_mugs:[/orange_red1]\n"
msg = "[dark_cyan]FabSim3 installation was successful :heavy_check_mark:[/dark_cyan]\n\n"
msg += "In order to use fabsim command anywhere in your PC, you need to "
msg += "update the [blue]PATH[/blue] and [blue]PYTHONPATH[/blue] environmental variables.\n\n"
msg += "\t[red1]export[/red1] [blue]PATH[/blue]={}/fabsim/bin:[blue]$PATH[/blue]\n".format(
    FS3_env.FabSim3_PATH
)
msg += "\t[red1]export[/red1] [blue]PYTHONPATH[/blue]={}:[blue]$PYTHONPATH[/blue]\n\n".format(
    FS3_env.FabSim3_PATH
)

# Check if ~/.local/bin is already in PATH
local_bin_path = os.path.expanduser("~/.local/bin")
if local_bin_path not in os.environ["PATH"]:
    msg += "\t[red1]export[/red1] [blue]PATH[/blue]=~/.local/bin:[blue]$PATH[/blue]\n"

msg += "\nThe last line is added because the required packages are "
msg += 'installed with flag "--user" which makes pip install packages '
msg += "in your home directory instead of system directory."

This approach ensures that the message for updating $PATH only includes ~/.local/bin if it’s not already in the user’s $PATH. I’ve tested this change, and it effectively prevents duplicate entries.

Would someone with commit access be able to review and apply this update? Please let me know if there’s anything further I can assist with!

Thank you!

**Comment by mzrghorbani** [comment]
The modification is committed. Thank you!
